go:
  name: go development
  color: ossen

game:
  name: game development
  color: limoen

devops:
  name: devops
  color: oceaan

python:
  name: python development
  color: bruin

java:
  name: java development
  color: groen

web:
  name: web development
  color: oranje

service:
  name: service development
  color: blauw

consultancy:
  name: consultancy
  color: fuchsia

#research:
#  name: research
#  color: bruin

#fun:
#  name: fun
#  color: ossen


