web:
  name: web development
  color: oranje

java:
  name: java development
  color: groen

python:
  name: python development
  color: bruin

service:
  name: service development
  color: blauw

go:
  name: go development
  color: ossen

devops:
  name: devops
  color: oceaan

game:
  name: game development
  color: limoen

consultancy:
  name: consultancy
  color: fuchsia

research:
  name: research
  color: bruin

fun:
  name: fun
  color: ossen


